name: Publish Docker image to ECR Repository and run Terraform

on:
  push:
    branches:
      - main
      - '*'
      - '*/'
      - '**'

jobs:
  publish-to-ecr:
    name: Push Docker image to ECR repository
    runs-on: ubuntu-latest
    env:
      ECR_REPO: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-kandidatnr-2038

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Should compile and build for any branch.
      - name: Compile and build docker container image
        run: docker build . -t ppe-detection-test

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com

      # Should only publish on push to main
      - name: Publish to ECR repository
        if: github.ref == 'refs/heads/main'
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag ppe-detection-test $ECR_REPO:$rev
          docker push $ECR_REPO:$rev
          docker tag ppe-detection-test $ECR_REPO:latest
          docker push $ECR_REPO:latest

      - name: Terraform init and apply on push to main
        if: github.ref == 'refs/heads/main'
        # If not using default values use:
        # Another solution is using variables under an env: and then reference to it with $<variable-name>
        # terraform apply -var="service_name=<name>" -var="aws_iam_role_name=<name>" -var="aws_iam_policy_name=<name>" -var="port=<name>"  -auto-approve
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./infra
