name: Publish Docker image to ECR Repository and run Terraform

on:
  push:
    branches:
      - main
      - '*'
      - '*/'
      - '**'

jobs:
  dockerize-ecr-terraform:
    name: Push Docker image to ECR repository
    runs-on: ubuntu-latest
    env:
      ECR_REPO: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-kandidatnr-2038
      SERVICE_NAME: app-runner-kandidatnr-2038
      AWS_IAM_ROLE_NAME: iam-role-2038
      AWS_IAM_POLICY_NAME: policy-app-service-2038
      PORT: 8080

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Should compile and build for any branch.
      - name: Compile and build docker container image
        run: docker build . -t ppe-detection-test

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com

      # Should only publish on push to main
      - name: Publish to ECR repository
        if: github.ref == 'refs/heads/main'
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag ppe-detection-test $ECR_REPO:$rev
          docker tag ppe-detection-test $ECR_REPO:latest
          docker push $ECR_REPO:$rev
          docker push $ECR_REPO:latest

      # Push to ECR, run terraform init and apply should all be done when pushing to main. They could be in the same run: | script
      # But to make it a bit easier for the eyes, i divided them into separate ones. Some duplicate code but easier to read and see which part is running.

      - name: Terraform init
        if: github.ref == 'refs/heads/main'
        run: terraform init
        working-directory: ./infra

      - name: Terraform apply on push to main
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var="image_tag=$(git rev-parse --short HEAD)" -var="service_name=$SERVICE_NAME" -var="aws_iam_role_name=$AWS_IAM_ROLE_NAME" -var="aws_iam_policy_name=$AWS_IAM_POLICY_NAME" -var="port=$PORT"  -auto-approve
#        run: terraform apply -var="service_name=$SERVICE_NAME" -var="aws_iam_role_name=$AWS_IAM_ROLE_NAME" -var="aws_iam_policy_name=$AWS_IAM_POLICY_NAME" -var="port=$PORT"  -auto-approve
        working-directory: ./infra