name: Publish Docker image to ECR Repository

on:
  push:
    branches:
      - main
      - '*'
      - '*/'
      - '**'

jobs:
  publish-to-ecr:
    name: Push Docker image to ECR repository
    runs-on: ubuntu-latest
    env:
      ECR_REPO: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-kandidatnr-2038

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS-REGION: eu-west-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 244530008913.dkr.ecr.eu-west-1.amazonaws.com

      # Should compile and build for any branch.
      - name: Compile and build docker container image
        run: docker build . -t ppe-detection-test

      - name: Push to main
        if: github.ref == 'refs/heads/main'
        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag ppe-detection-test $ECR_REPO:$rev
          docker push $ECR_REPO:$rev
          docker tag ppe-detection-test $ECR_REPO:latest
          docker push $ECR_REPO:latest