name: Publish Docker image to ECR Repository

on:
  push:
    branches:
      - main

jobs:
  publish-to-ecr:
    name: Push Docker image to ECR repository
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Compile and build docker container image
        run: docker build . -t ppe-detection-test

      - name: Publish to ECR repo only if pushing to main
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ECR_REPO: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/ecr-kandidatnr-2038

        run: |
          rev=$(git rev-parse --short HEAD)
          docker tag ppe-detection-test $ECR_REPO:$rev
          docker push $ECR_REPO:$rev
          docker tag ppe-detection-test $ECR_REPO:latest
          docker push $ECR_REPO:latest